services:
  codex:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    container_name: codex-runner
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CODEX_MODEL=${CODEX_MODEL:-gpt-4.1}
      - SANDBOX_MODE=${SANDBOX_MODE:-danger-full-access}
      - NETWORK_ACCESS=${NETWORK_ACCESS:-true}
      - MODEL_REASONING_EFFORT=${MODEL_REASONING_EFFORT:-high}
      - MODEL_REASONING_SUMMARY=${MODEL_REASONING_SUMMARY:-auto}
      - AUTONOMY=${AUTONOMY:-full}
    volumes:
      # Mount your repo dynamically on run
      # Example: docker compose run -v ~/Projects/foo:/workspace codex
      - ./prompts:/prompts:ro
    working_dir: /workspace
    tty: true
    stdin_open: true
    # No need to override USER here — Dockerfile already sets ubuntu
    command: ["/bin/bash"]
